import { Listing } from './types';

export const mockListings: Listing[] = [
  {
    id: '1',
    title: 'Tech Startup CEOs',
    description: 'Comprehensive list of CEOs from Series A to C tech startups',
    industry: 'Technology',
    jobTitle: 'C-Level',
    volume: '1000-5000',
    type: 'Email',
    price: 2999,
    isVerified: true,
    seller: {
      id: 'seller1',
      name: 'DataPro Solutions',
      rating: 4.8,
    },
  },
  {
    id: '2',
    title: 'Healthcare Professionals',
    description: 'Database of healthcare professionals across major US hospitals',
    industry: 'Healthcare',
    jobTitle: 'Individual Contributor',
    volume: '5000-10000',
    type: 'Phone',
    price: 4999,
    isVerified: true,
    seller: {
      id: 'seller2',
      name: 'MedData Inc',
      rating: 4.5,
    },
  },
  {
    id: '3',
    title: 'Finance Directors',
    description: 'List of finance directors from Fortune 500 companies',
    industry: 'Finance',
    jobTitle: 'VP/Director',
    volume: '10000+',
    type: 'LinkedIn',
    price: 7999,
    isVerified: true,
    seller: {
      id: 'seller3',
      name: 'FinanceLeads',
      rating: 4.9,
    },
  },
  {
    id: '4',
    title: 'Retail Managers',
    description: 'Database of retail store managers from top retail chains',
    industry: 'Retail',
    jobTitle: 'Manager',
    volume: '0-1000',
    type: 'Email',
    price: 1999,
    isVerified: false,
    seller: {
      id: 'seller4',
      name: 'RetailData Co',
      rating: 4.2,
    },
  },
  {
    id: '5',
    title: 'Manufacturing Engineers',
    description: 'List of manufacturing engineers from automotive industry',
    industry: 'Manufacturing',
    jobTitle: 'Individual Contributor',
    volume: '1000-5000',
    type: 'Phone',
    price: 3499,
    isVerified: true,
    seller: {
      id: 'seller5',
      name: 'IndustryLeads',
      rating: 4.6,
    },
  },
  {
    id: '6',
    title: 'Education Administrators',
    description: 'Database of school and university administrators',
    industry: 'Education',
    jobTitle: 'Manager',
    volume: '5000-10000',
    type: 'Email',
    price: 2499,
    isVerified: true,
    seller: {
      id: 'seller6',
      name: 'EduData Solutions',
      rating: 4.7,
    },
  },
]; 